function [metList, vmhList] = loadADRCMets()

% Metabolites that potentially associated with either global cognition,
% age, or APOE genotype (p<0.1).
hensen2024Mets = {...
    '2hb','2-hydroxybutyrate';...
    '3dhchol','3-Dehydrocholate';...
    '7ocholate','3-7-Dehydrocholate';...
    'creat','Creatine';...
    'glc_D','D-glucose';...
    'dchac','Deoxycholate';...
    'HC02191','Lithocholate';...
    'fald','Formaldehyde';
    'for','Formate';...
    'isochol','Isocholate';...
    'arg_L','L-Arginine';...
    'ile_L','L-isoleucine';...
    'phe_L','L-phenylalanine';...
    'lys_L','L-lysine';...
    'ppa','Proprionate';...
    'amet','S-Adenosyl-L-methionine';...
    'taur','Taurine';...
    'tyr_L','L-tyrosine';...
    'dopa','Dopamine';...
    'nrpphr','Norepinephrine';...
    'uchol','Ursocholate'...
    };

% Metabolites identified in exploratory run on ADRC data. 
% Threshold for p<0.05.
metsExploratory = {...
    % Tim Hensen
    'HC02192','Lithocholyltaurine';...
    'lca3s','Lithocholic acid 3-sulfate';...
    %'M02155','Hyodesoxycholic Acid';...
    'HC02193','glycolithocholate';...
    'phe_L','L-phenylalanine';...
    'cdca3g','Deoxycholic acid-3glucuronide, CDA-3G';...
    'tdechola','Taurodeoxycholic acid';...
    '3dhdchol','3-Dehydro-Deoxycholate';...
    'gdca3s','Glycodeoxycholic acid 3-sulfate';...
    'dca3s','Deoxycholic acid 3-sulfate';...
    'tdca3s','Taurodeoxycholic acid 3-sulfate';...
    'hdca6g','Hyodeoxycholic acid-6glucuronide, HDCA-6G';...
    'homoval','Homovanillate';...
    'HC02191','Lithocholate';...
    'lca3g','Lithocholic acid-3glucuronide, CDCA-3G';...
    'dca24g','Deoxycholic acid-24glucuronide, CDA-24G';...
    'adrnl','Epinephrine';...
    'mepi','Metanephrine';...
    % Cornelia Sivi 
    '34dhoxpeg','3,4-Dihydroxyphenylglycol';...
    % Jonas Widder
    %'3h3mop','(R)-3-Hydroxy-3-methyl-2-oxopentanoate';... 
    '3mop','3-Methyl-2-Oxovaleric Acid'};


% Concatinate metabolite lists
metList = [hensen2024Mets; metsExploratory];
% Remove duplicates
[~,uniqueRow] = unique(metList(:,1));

% Set output
metList = metList(uniqueRow,:);

vmhList = metList(:,1);
end
